from .aquila import AquilaAWQForCausalLM
from .baichuan import BaichuanAWQForCausalLM
from .bloom import BloomAWQForCausalLM
from .deepseek import DeepseekAWQForCausalLM
from .falcon import FalconAWQForCausalLM
from .gemma import GemmaAWQForCausalLM
from .gpt_bigcode import GptBigCodeAWQForCausalLM
from .gpt_neox import GPTNeoXAWQForCausalLM
from .gptj import GPTJAWQForCausalLM
from .llama import LlamaAWQForCausalLM
from .llava import LlavaAWQForCausalLM
from .mistral import MistralAWQForCausalLM
from .mixtral import MixtralAWQForCausalLM
from .mpt import MptAWQForCausalLM
from .opt import OptAWQForCausalLM
from .qwen import QwenAWQForCausalLM
from .qwen2 import Qwen2AWQForCausalLM
from .stablelm import StableLmAWQForCausalLM
from .yi import YiAWQForCausalLM
